-- Migration: 0001 Initial Schema
-- Summary: Creates the base tables for jobs, job_events, and artifacts

-- Create jobs table
CREATE TABLE IF NOT EXISTS jobs (
  run_id text PRIMARY KEY,
  project_spec jsonb NOT NULL,
  owner_id uuid,
  status text DEFAULT 'pending',
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create job_events table
CREATE TABLE IF NOT EXISTS job_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id text NOT NULL REFERENCES jobs(run_id) ON DELETE CASCADE,
  bot_name text NOT NULL,
  event_type text NOT NULL,
  payload jsonb,
  owner_id uuid,
  created_at timestamptz DEFAULT now()
);

-- Create artifacts table
CREATE TABLE IF NOT EXISTS artifacts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id text NOT NULL REFERENCES jobs(run_id) ON DELETE CASCADE,
  kind text NOT NULL,
  url text,
  meta jsonb,
  owner_id uuid,
  file_size bigint,
  content_type text,
  checksum text,
  created_at timestamptz DEFAULT now()
);

-- Create prompts table (for AI prompts and copy)
CREATE TABLE IF NOT EXISTS prompts (
  id text PRIMARY KEY,
  category text NOT NULL,
  context text NOT NULL,
  prompt_text text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_jobs_owner_id ON jobs(owner_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_owner_status ON jobs(owner_id, status);
CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs(created_at);

CREATE INDEX IF NOT EXISTS idx_job_events_run_id ON job_events(run_id);
CREATE INDEX IF NOT EXISTS idx_job_events_owner_id ON job_events(owner_id);
CREATE INDEX IF NOT EXISTS idx_job_events_created_at ON job_events(created_at);

CREATE INDEX IF NOT EXISTS idx_artifacts_run_id ON artifacts(run_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_owner_id ON artifacts(owner_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_created_at ON artifacts(created_at);
CREATE INDEX IF NOT EXISTS idx_artifacts_owner_created ON artifacts(owner_id, created_at);

-- Add comments for documentation
COMMENT ON TABLE jobs IS 'Stores pipeline job information';
COMMENT ON TABLE job_events IS 'Stores events generated by bots during pipeline execution';
COMMENT ON TABLE artifacts IS 'Stores artifacts generated by the pipeline';
COMMENT ON TABLE prompts IS 'Stores AI prompts and application copy';

