-- Migration: 0001 Initial Schema (Safe)
-- Summary: Creates the base tables for jobs, job_events, and artifacts (safe version)

-- Create jobs table with only essential columns first
CREATE TABLE IF NOT EXISTS jobs (
  run_id text PRIMARY KEY,
  project_spec text, -- Using text instead of jsonb for compatibility
  created_at timestamptz DEFAULT now()
);

-- Create job_events table with only essential columns
CREATE TABLE IF NOT EXISTS job_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id text,
  bot_name text,
  event_type text,
  payload text,
  created_at timestamptz DEFAULT now()
);

-- Create artifacts table with only essential columns
CREATE TABLE IF NOT EXISTS artifacts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id text,
  kind text,
  url text,
  meta text,
  created_at timestamptz DEFAULT now()
);

-- Create prompts table (for AI prompts and copy)
CREATE TABLE IF NOT EXISTS prompts (
  id text PRIMARY KEY,
  category text NOT NULL,
  context text NOT NULL,
  prompt_text text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Note: Additional columns (owner_id, status, etc.) are added by subsequent migrations

-- Add comments for documentation
COMMENT ON TABLE jobs IS 'Stores pipeline job information';
COMMENT ON TABLE job_events IS 'Stores events generated by bots during pipeline execution';
COMMENT ON TABLE artifacts IS 'Stores artifacts generated by the pipeline';
COMMENT ON TABLE prompts IS 'Stores AI prompts and application copy';

