name: _deploy
on: { workflow_call: {} }
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy here (Vercel/Fly/Render) via OIDC"